variables:
  GIT_URL: "ssh://$BITBUCKET_URL/qsdk/$CLIENT_NUMBER.git"
  ARTIFACTORY_URL: "http://localhost:4040/root/q2"
  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  
cache:
  key: "$CI_PIPELINE_ID"
  paths:
    - .cache/pip
    - .env

before_script:
  - python3.9 --version
  - python3.9 -m venv .env
  - source .env/bin/activate

stages:
  - build
  - test
  - mirror
  - dockerize
  - deploy

q2 check:
  stage: build
  tags:
    - sdk-dev
  script:
    - pip install --cache-dir $PIP_CACHE_DIR -i $ARTIFACTORY_URL -r requirements.txt
    - q2 check

q2 test:
  stage: test
  tags:
    - sdk-dev
  script:
    - q2 test -W ignore::DeprecationWarning
    
q2 lint:
  stage: test
  tags:
    - sdk-dev
  script:
    - q2 lint
  allow_failure: true

mirror:
  stage: mirror
  tags:
    - sdk-corp
  script:
    - git push $GIT_URL +refs/remotes/origin/*:refs/heads/*

dockerize:
  stage: dockerize
  tags:
    - sdk-corp
  script:
    - /opt/gitlab-runner-env/bin/python /usr/local/bin/gitlab-runner-deploy.py dockerize $CLIENT_NUMBER --commit_hash $CI_COMMIT_REF_NAME
  environment:
    name: $CLIENT_NUMBER Staging
  only:
    - master

deploy:
  stage: deploy
  tags:
    - sdk-staging
  script:
    - COMMIT_TIME=$(TZ=UTC git log -1 --format=%cd --date=format-local:%Y-%m-%d_%H%M%S)
    - /opt/gitlab-runner-env/bin/python /usr/local/bin/gitlab-runner-deploy.py deploy $CLIENT_NUMBER $VAULT_KEY $COMMIT_TIME --cdm_fi_number $FI_NUMBER
  environment:
    name: $CLIENT_NUMBER Staging
  only:
    - master
